### ISSUE TITLE
Doesn't work with rubocop v1.31

### ISSUE THREAD

**Issue by azrsh** [xinminlabs/rubocop-config-rufo#4]
## What's happening

This gem doesn't work with the latest rubocop as some cops have been renamed and obsoleted.

- https://github.com/rubocop/rubocop/blob/master/relnotes/v0.68.0.md
  - `Layout/FirstParameterIndentation` -> `Layout/IndentFirstArgument`
  - `Layout/IndentArray` -> `Layout/IndentFirstArrayElement`
  - `Layout/IndentHash` -> `Layout/IndentFirstHashElement`
- https://github.com/rubocop/rubocop/blob/master/relnotes/v0.77.0.md
  - `Layout/AlignArray` -> `Layout/ArrayAlignment`
  - `Layout/AlignHash` -> `Layout/HashAlignment`.
  - `Layout/IndentAssignment` -> `Layout/AssignmentIndentation`.
  - `Layout/Tab` -> `Layout/IndentationStyle`.
  - `Layout/TrailingBlankLines` -> `Layout/TrailingEmptyLines`.

## What to do

Here's what I think I should do: 

1. Add rubocop version constraint to gemspec (`< 0.68.0`)
2. Replace cops which is changed in v0.68.0 and Fix rubocop version constraint (`>=0.68.0, < 0.77.0`)
3. Replace cops which is changed in v0.77.0 and Fix rubocop version constraint (`~> 1.31.0`)

**Comment by azrsh** [comment]
@flyerhzm (maintainer of this repository?)
If this plan is ok, I will send PRs and you can assign me to this issue! Thanks!

**Comment by flyerhzm** [comment]
@azarashi2931 sorry, we didn't use rufo anymore, I'll archive this project.
